export const specialties = [
    {
        id: '1',
        slug: 'cardiologia',
        name: 'Cardiología',
        shortDescription: 'Diagnóstico y tratamiento de enfermedades cardiovasculares.',
        fullDescription: 'Atención especializada para la prevención, diagnóstico y tratamiento de enfermedades del corazón y sistema circulatorio.',
        fontIcon: 'heart-rate-monitor',
        coverImage: 'https://images.unsplash.com/photo-1628348070889-cb656235b4eb?w=800&h=400&fit=crop&auto=format',
        procedures: ['Electrocardiograma', 'Ecocardiograma', 'Holter', 'Prueba de esfuerzo'],
        relatedDoctorIds: ['1'],
        featured: true,
        order: 1,
        preferred: true,
    },
    {
        id: '2',
        slug: 'cirugia-cardiovascular',
        name: 'Cirugía cardiovascular',
        shortDescription: 'Procedimientos quirúrgicos del corazón y vasos sanguíneos.',
        fullDescription: 'Tratamientos quirúrgicos especializados para patologías cardiovasculares complejas.',
        fontIcon: 'heart-plus',
        coverImage: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=400&fit=crop&auto=format',
        procedures: ['Bypass coronario', 'Reemplazo valvular', 'Cirugía vascular'],
        relatedDoctorIds: [],
        featured: true,
        order: 2,
    },
    {
        id: '3',
        slug: 'cirugia-cabeza-cuello-maxilofacial',
        name: 'Cirugía de cabeza, cuello y maxilofacial',
        shortDescription: 'Cirugía reconstructiva y funcional de cabeza y cuello.',
        fullDescription: 'Atención especializada para patologías, traumatismos y reconstrucción maxilofacial.',
        fontIcon: 'scan',
        coverImage: 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=800&h=400&fit=crop&auto=format',
        procedures: ['Cirugía maxilofacial', 'Reconstrucción facial', 'Biopsias'],
        relatedDoctorIds: [],
        featured: true,
        order: 3,
    },
    {
        id: '4',
        slug: 'cirugia-general',
        name: 'Cirugía general',
        shortDescription: 'Procedimientos quirúrgicos para diversas patologías.',
        fullDescription: 'Cirugías programadas y de emergencia con técnicas modernas y seguras.',
        fontIcon: 'scissors',
        coverImage: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&h=400&fit=crop&auto=format',
        procedures: ['Hernias', 'Apendicectomía', 'Colecistectomía'],
        relatedDoctorIds: [],
        featured: true,
        order: 4,
        preferred: true,
    },
    {
        id: '5',
        slug: 'cirugia-oncologica',
        name: 'Cirugía oncológica',
        shortDescription: 'Tratamiento quirúrgico del cáncer.',
        fullDescription: 'Procedimientos orientados al tratamiento integral de enfermedades oncológicas.',
        fontIcon: 'shield-plus',
        coverImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&h=400&fit=crop&auto=format',
        procedures: ['Resección tumoral', 'Biopsias', 'Cirugía oncológica avanzada'],
        relatedDoctorIds: [],
        featured: true,
        order: 5,
    },
    {
        id: '6',
        slug: 'cirugia-pediatrica',
        name: 'Cirugía pediátrica',
        shortDescription: 'Procedimientos quirúrgicos para niños y adolescentes.',
        fullDescription: 'Atención quirúrgica especializada para pacientes pediátricos.',
        fontIcon: 'baby-carriage',
        coverImage: 'https://images.unsplash.com/photo-1581056771107-24ca5f033842?w=800&h=400&fit=crop&auto=format',
        procedures: ['Cirugía neonatal', 'Corrección de malformaciones'],
        relatedDoctorIds: [],
        featured: true,
        order: 6,
    },
    {
        id: '7',
        slug: 'endocrinologia',
        name: 'Endocrinología',
        shortDescription: 'Atención de trastornos hormonales y metabólicos.',
        fullDescription: 'Diagnóstico y tratamiento de enfermedades endocrinas como diabetes y tiroides.',
        fontIcon: 'activity-heartbeat',
        coverImage: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=400&fit=crop&auto=format',
        procedures: ['Control de diabetes', 'Evaluación tiroidea'],
        relatedDoctorIds: [],
        featured: true,
        order: 7,
        preferred: true,
    },
    {
        id: '8',
        slug: 'gastroenterologia',
        name: 'Gastroenterología',
        shortDescription: 'Diagnóstico y tratamiento de enfermedades digestivas.',
        fullDescription: 'Atención integral del aparato digestivo y órganos asociados.',
        fontIcon: 'pill',
        coverImage: 'https://images.unsplash.com/photo-1580281657527-47eec6d9b4f1?w=800&h=400&fit=crop&auto=format',
        procedures: ['Endoscopia', 'Colonoscopia'],
        relatedDoctorIds: [],
        featured: true,
        order: 8,
    },
    {
        id: '9', slug: 'ginecologia', name: 'Ginecología',
        shortDescription: 'Salud integral de la mujer.',
        fullDescription: 'Atención preventiva, diagnóstica y terapéutica para la salud femenina.',
        fontIcon: 'gender-female',
        coverImage: 'https://images.unsplash.com/photo-1638202993928-7267aad84c31?w=800&h=400&fit=crop&auto=format',
        procedures: ['Papanicolaou', 'Colposcopía', 'Control prenatal'],
        relatedDoctorIds: [], featured: true, order: 9,
        preferred: true,
    },
    {
        id: '10', slug: 'medicina-alternativa-y-complementaria', name: 'Medicina alternativa y complementaria',
        shortDescription: 'Terapias complementarias para el bienestar integral.',
        fullDescription: 'Enfoque integrativo orientado a mejorar la calidad de vida del paciente.',
        fontIcon: 'nurse',
        coverImage: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800&h=400&fit=crop&auto=format',
        procedures: ['Acupuntura', 'Terapias complementarias'],
        relatedDoctorIds: [], featured: false, order: 10,
    },
    {
        id: '11', slug: 'medicina-interna', name: 'Medicina interna',
        shortDescription: 'Atención integral de enfermedades del adulto.',
        fullDescription: 'Evaluación y tratamiento de patologías complejas y crónicas.',
        fontIcon: 'stethoscope',
        coverImage: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&h=400&fit=crop&auto=format',
        procedures: ['Chequeos', 'Manejo de enfermedades crónicas'],
        relatedDoctorIds: [], featured: true, order: 11,
        preferred: true,
    },
    {
        id: '12', slug: 'neurologia', name: 'Neurología',
        shortDescription: 'Diagnóstico y tratamiento de enfermedades neurológicas.',
        fullDescription: 'Atención especializada para trastornos del sistema nervioso.',
        fontIcon: 'brain',
        coverImage: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&h=400&fit=crop&auto=format',
        procedures: ['Electroencefalograma', 'Evaluación neurológica'],
        relatedDoctorIds: [], featured: true, order: 12,
        preferred: true,
    },
    {
        id: '13', slug: 'nutricion', name: 'Nutrición',
        shortDescription: 'Planes alimenticios personalizados.',
        fullDescription: 'Asesoría nutricional para todas las etapas de la vida.',
        fontIcon: 'apple',
        coverImage: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=400&fit=crop&auto=format',
        procedures: ['Evaluación nutricional', 'Dietas personalizadas'],
        relatedDoctorIds: [], featured: true, order: 13,
        preferred: true,
    },
    {
        id: '14', slug: 'odontologia', name: 'Odontología',
        shortDescription: 'Cuidado integral de la salud bucal.',
        fullDescription: 'Prevención y tratamiento de enfermedades dentales y orales.',
        fontIcon: 'dental',
        coverImage: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=800&h=400&fit=crop&auto=format',
        procedures: ['Limpieza dental', 'Endodoncia', 'Ortodoncia'],
        relatedDoctorIds: [], featured: true, order: 14,
        preferred: true,
    },
    {
        id: '15', slug: 'otorrinolaringologia', name: 'Otorrinolaringología',
        shortDescription: 'Especialidad de oído, nariz y garganta.',
        fullDescription: 'Diagnóstico y tratamiento de patologías ORL.',
        fontIcon: 'ear',
        coverImage: 'https://images.unsplash.com/photo-1581595219315-a187dd40c322?w=800&h=400&fit=crop&auto=format',
        procedures: ['Audiometría', 'Endoscopia nasal'],
        relatedDoctorIds: [], featured: true, order: 15,
    },
    {
        id: '16', slug: 'pediatria', name: 'Pediatría',
        shortDescription: 'Atención médica para niños y adolescentes.',
        fullDescription: 'Seguimiento integral del crecimiento y desarrollo infantil.',
        fontIcon: 'baby-carriage',
        coverImage: 'https://images.unsplash.com/photo-1581056771107-24ca5f033842?w=800&h=400&fit=crop&auto=format',
        procedures: ['Control de niño sano', 'Vacunación'],
        relatedDoctorIds: [], featured: true, order: 16,
        preferred: true,
    },
    {
        id: '17', slug: 'psicologia', name: 'Psicología',
        shortDescription: 'Atención y acompañamiento en salud mental.',
        fullDescription: 'Evaluación, orientación y terapia psicológica.',
        fontIcon: 'mood-smile',
        coverImage: 'https://images.unsplash.com/photo-1573497620053-ea5300f94f21?w=800&h=400&fit=crop&auto=format',
        procedures: ['Psicoterapia', 'Evaluación psicológica'],
        relatedDoctorIds: [], featured: true, order: 17,
        preferred: true,
    },
    {
        id: '18', slug: 'reumatologia', name: 'Reumatología',
        shortDescription: 'Diagnóstico y tratamiento de enfermedades reumáticas.',
        fullDescription: 'Atención especializada para articulaciones, músculos y tejido conectivo.',
        fontIcon: 'hand-stop',
        coverImage: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=800&h=400&fit=crop&auto=format',
        procedures: ['Artritis', 'Osteoporosis'],
        relatedDoctorIds: [], featured: false, order: 18,
    },
    {
        id: '19', slug: 'traumatologia', name: 'Traumatología',
        shortDescription: 'Tratamiento de lesiones musculoesqueléticas.',
        fullDescription: 'Atención especializada para fracturas, lesiones y rehabilitación.',
        fontIcon: 'bone',
        coverImage: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=400&fit=crop&auto=format',
        procedures: ['Fracturas', 'Artroscopía', 'Rehabilitación'],
        relatedDoctorIds: [], featured: true, order: 19,
        preferred: true,
    },
];
export default specialties;
